#!/bin/sh
#                                                   -*-Shell-script-*-

SECTION_FILES="$@"

# section NUMBER TITLE DESCRIPTION
# --------------------------------
# Create a section in the document with the TITLE, then add include
# macros for any input file matching the section NUMBER.  The section
# is given a brief DESCRIPTION.
section() {
    number=$1; shift
    title=$1; shift
    desc=$1; shift

    echo "== $title =="
    echo
    echo "$desc"
    echo

    for f in "$SECTION_FILES"; do
        if echo $f | grep "^uc$number.*\\.txt$" > /dev/null; then
            echo "include::$f[leveloffset=2]"
            echo
        fi
    done
}


cat <<EOF
= Use Cases for Electronic Design Datastructures =

// This file is automatically generated; do not edit it directly.

[NOTE]
We should add an explanatory preamble here.

EOF
section 01 "Hierarchy" \
    "Use cases for hierarchical schematics."
section 02 "Connectivitiy" \
    "Use cases for on-line connectivity tracking."
section 03 "Graphical representations" \
    "Use cases for graphical representations of schematics."
section 04 "PCB design" \
    "Use cases for workflows targetting Printed Circuit Board production."
section 05 "ASIC design" \
    "Use cases for workflows targetting Application-Specific Integrated Circuits."
section 06 "Simulation" \
    "Use cases for workflows targetting circuit simulation."
